### ISSUE TITLE
Request for comments: allow users to export plain React components

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar-react-adapter#27]
This is just an idea; please let me know what you think!

Let me start with a sample from the [React docs](https://facebook.github.io/react/docs/state-and-lifecycle.html#adding-lifecycle-methods-to-a-class):

```js
class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }

  componentDidMount() {
  }

  componentWillUnmount() {
  }

  render() {
    return (
      <div>
        <h1>Hello, world!</h1>
        <h2>It is {this.state.date.toLocaleTimeString()}.</h2>
      </div>
    );
  }
}
```

I think it would be nice if we could just export a component like that and use it as a Laxar widget without any modification. Like `export default class Clock extends …`.
We would still use `ReactDom.render()` in `domAttachTo` but create the virtual DOM differently (see below) and add `ReactDom.unmountComponentAtNode()` in `domDetach`. That should also take care of automatically calling the lifecycle hooks `componentDidMount` and `componentWillUnmount`.
The user can then use `this.setState` to update the component state and cause it to re-render without needing to use the `axReactRender` injection to trigger rendering manually. This scheme should also be compatible with functional components (plain functions, not inheriting from `React.Component`).

Caveats: I have no idea for the injections yet. Have not thought much about compatibility with older React widgets either.

```js
// in domAttachTo, with module being the default export of the widget module
ReactDom.render( React.createElement( module, {}, null ), anchorElement );

// in domDetach:
ReactDom.unmountComponentAtNode( anchorElement );
```

Is this worth exploring further?

**Comment by x1B** [comment]
I think that this is a great idea. My thought on injections would be to use "magic" props. Not sure if that would work though.

**Comment by alex3683** [comment]
I like this idea too. I'd suggest to start a prototype and as soon as we are confronted with the injection thing, we might try to find a solution together.

**Comment by jpommerening** [comment]
Ok, I'll build a prototype!

**Comment by jpommerening** [comment]
Holy moly.

Upgrading a widget to export a component can be non trivial, to say the least. The following approach kind of worked:

- export a new component class like so:
   ```js
   export default class EventsDisplayWidget extends React.Component {
      // EDIT: look further down & at the README for the final injection syntax!
      static get injections() {
        return [ 'axContext', 'axReactRender' ];
      }
      get injections() {
         return this.constructor.injections.map( name => this.props[ name ] );
      }
   
      constructor( props ) {
         super( props )
         const [ context, reactRender ] = this.injections;
      }
   
      render() {
         const [ context, reactRender ] = this.injections;
      }
   }
   ```
- next, extract all "internal" components defined inside the `create()` closure to the outer scope; pass in all required state with props
- move the body of the render function to the render method
- move the remainder of the `create()` function's body to the constructor
- in the constructor, export anything that is needed by the render method by assigning properties to `this`

The result should work, but probably requires some clean up. For example, in-place modification of the model should be replaced with state updates, ideally removing the need to use `reactRender` at all.

Maybe we can replace the injection boilerplate with something that can be exported from `laxar-react-adapter`. If classes were hoisted, an `inject( Component, 'x', 'y', 'z', ... )` method to define these properties could be beneficial, but, alas, that does not work.

**Comment by jpommerening** [comment]
Okay, injection time! 💉

@x1B @alex3683 @jonaswjs 

It [seems to be customary](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#supported-language-features-and-polyfills) to use [`babel-plugin-transform-class-properties`](https://babeljs.io/docs/plugins/transform-class-properties/) when using React with JSX and Flow.

[Class fields](https://tc39.github.io/proposal-class-fields/) enable us to define regular and static properties in our classes. They are currently in Stage 2 of the proposal pipeline, so syntax and semantics _might_ still change in the future. We could write injections like this:

```js
export default class MyWidget extends React.Component {
   static injections = [ 'axContext', 'axLog' ];

   render() {
      const [ context, log ] = this.props.injections;
      return <blink>Hi.</blink>;
   }
}
```

Without the class properties transform, you'd have to assign `MyWidget.injections = [ ... ]` _after_ the definition, which is bothersome, but works.

The injection mechanism has changed as well: Instead of passing each injection as a named property, they are passed as an array via the `injection` property. This is as simple as it gets.

Any thoughts?

----

Edit: This also works with “functional” components:

```js
MyWidget.injections = [ 'axContext', 'axLog' ];
export default function MyWidget( props ) {
   const [ context, log ] = props.injections;
   return <blink>Hi.</blink>;
}
```

**Comment by x1B** [comment]
@jpommerening Looks simple; I like it. I would assume that this syntax will not be chaning to much anymore (similar to Object rest/spread).

**Comment by jpommerening** [comment]
@x1B Yep. There's still some discussion about what happens when you assign functions that way but the syntax for simple properties seems stable.

If we want to make the relation to `laxar-react-adapter` more explicit, we could export `injections` as a `Symbol` and use computed properties:

```js
import { injections } from 'laxar-react-adapter';
export default class MyWidget extends React.Component {
   static [ injections ] = [ 'axContext', 'axLog' ];
}
```

**Comment by jpommerening** [comment]
I went for the `Symbol` injection syntax and inlined a, well, not really a polyfill, but a fallback. Let's call it a phonyfill. I also fixed the backwards-compatibility layer (`module.create( ...injections )`) so that all tests pass and it should behave just like before. The README now reflects those changes.

This change is _not breaking_, but #21 still is.

### NEW FEATURE

Widgets can now be implemented as React components! See README for details.
Just refer to the code below for a (mosty) self-explanatory example:

```js
import React from 'react';
import { injections } from 'laxar-react-adapter';

export default MyWidget extends React.Component {
   static [ injections ] = [ 'axFeatures', 'axEventBus' ];

   constructor( props ) {
      const [ features, eventBus ] = props.injections;
      super( props );
      this.state = {
         counter: features.counter.startValue
      };
   }

   render() {
      const tick = () => {
         this.setState(prev => ({ counter: prev.counter + 1 }));
      };
      return <button onclick={tick}>{this.counter}</button>;
   }
}
```

**Comment by jpommerening** [comment]
Implemented on `master` -> v2
